DB:
  host : 'localhost'
  username : 'root'
  password : '123456'
  port : 3306
  database : 'meituan'

EMAIL:
  addr : '3184218074@qq.com'
  password : 'zvgvzwixizzbdfbi'

Redis:
  host : '127.0.0.0'
  port : 6379